version: "2"


services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web

  web:
    build: ./api
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn api.wsgi -b 0.0.0.0:8000
    volumes:
      - ./api:/webserver
      - ./static:/static
    #ports:
    #  - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db



volumes:
  db_data:
    external: true
