# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-20 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('doc_number', models.PositiveIntegerField(max_length=11, unique=True)),
            ],
        ),
    ]
