# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-20 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('doc_number', models.PositiveIntegerField(unique=True)),
                ('email_personal', models.EmailField(max_length=254)),
                ('emergency_tel_number', models.CharField(max_length=100)),
                ('personal_tel_number', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('waist', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='XS', max_length=2)),
                ('diet_description', models.CharField(max_length=500)),
                ('diocesis', models.CharField(max_length=250)),
                ('eslabon_number', models.PositiveIntegerField()),
                ('date_eslabon', models.DateField()),
                ('email_contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
