# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-17 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_pago_retiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 6, 17, 19, 55, 35, 833745, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
