# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-20 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20170520_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='personentity',
            name='is_acredited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personentity',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personentity',
            name='waist',
            field=models.CharField(choices=[('NO', 'NO'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='NO', max_length=2),
        ),
    ]
