# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-12 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20170705_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDiocesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Comision')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='talle',
            field=models.CharField(blank=True, choices=[('NO', 'NO'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='NO', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='detalle_dioc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.DetalleDiocesis'),
        ),
    ]
